apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: knowgo-score
  name: knowgo-score-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowgo-score
  template:
    metadata:
      labels:
        app: knowgo-score
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: knowgo-score
        image: adaptant/knowgo-score
        env:
        - name: KNOWGO_DB_URI
          value: "mysql+mysqlconnector://root:root@knowgo-mysql-service/knowgo?auth_plugin=mysql_native_password"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      restartPolicy: Always
