apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: knowgo-score
  name: knowgo-score-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowgo-score
  template:
    metadata:
      labels:
        app: knowgo-score
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{ if .Values.accelerators.gpu }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-gpu"
        {{ else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{ end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        {{- with .Values.podEnv }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.accelerators.gpu }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # k8s-auto-labeller
                  - key: accelerators/gpu
                    operator: Exists
      {{ end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
