apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.18.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
      - env:
        - name: SERVICE_IGNORE
          value: '"ignore"'
        image: consul:latest
        name: consul
        ports:
        - containerPort: 8500
        resources: {}
      restartPolicy: Always
status: {}
