apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: knowgo-mysql
  name: knowgo-mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.18.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: knowgo-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: SERVICE_3306_NAME
          value: knowgo-mysql
        image: adaptant/knowgo-mysql:latest
        name: knowgo-mysql
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
