apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.18.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: mqtt-broker
        image: eclipse-mosquitto:latest
        name: mqtt-broker
        ports:
        - containerPort: 1883
        resources: {}
      restartPolicy: Always
status: {}
