apiVersion: v1
name: knowgo-backend
description: A Helm Chart for deploying the KnowGo platform backend
version: 0.0.1
appVersion: 0.0.1
keywords:
  - backend
  - knowgo
sources:
  - https://github.com/pmundt/knowgo-helm-charts/tree/master/dev
maintainers:
  - name: Adaptant Labs
