apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: knowgo-mysql
  name: knowgo-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowgo-mysql
  template:
    metadata:
      labels:
        app: knowgo-mysql
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: adaptant/knowgo-mysql:latest
        name: knowgo-mysql
        ports:
        - containerPort: 3306
      restartPolicy: Always
