kind: Service
apiVersion: v1
metadata:
  name: knowgo-api-gateway-service
spec:
  selector:
    app: knowgo-api-gateway
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: https
